version: '3.9'
services:
  twitt-duck-db:
    image: postgres:16.1
    ports:
      - 5450:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: super-password-root
      POSTGRES_USER: root
      POSTGRES_DB: development
  twitt-duck-db-test:
    image: postgres:16.1
    ports:
      - 5451:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: super-password-root
      POSTGRES_USER: root
      POSTGRES_DB: development