import { ChakraProvider} from '@chakra-ui/react'
import {
  BottomBar,
  ChangeBackgroundPicture,
  Comment,
  CommentsList,
  ConfirmLogout,
  ConfirmRemoveRepost,
  CustomTabs,
  FormChangePassword,
  FormChangeProfileInfo,
  FormInput,
  GoogleButton,
  ImageVisor,
  Loader,
  Navbar,
  NewPost,
  Post,
  PostActions,
  PostsList,
  ProfileOption,
  ScrollToTop,
  SearchModal,
  SuggestPeople,
  Tendencies,
  Toolbar,
  UserAvatar,
  UserDetail,
  UserFeed,
} from './components'
import { theme } from './theme'

export {
  BottomBar,
  ChangeBackgroundPicture,
  Comment,
  CommentsList,
  ConfirmLogout,
  ConfirmRemoveRepost,
  ChakraProvider,
  CustomTabs,
  FormChangePassword,
  FormChangeProfileInfo,
  FormInput,
  GoogleButton,
  ImageVisor,
  Loader,
  Navbar,
  NewPost,
  Post,
  PostActions,
  PostsList,
  ProfileOption,
  ScrollToTop,
  SearchModal,
  SuggestPeople,
  Tendencies,
  theme,
  Toolbar,
  UserAvatar,
  UserDetail,
  UserFeed,
}
